# Generated by Django 4.0.10 on 2024-07-15 11:14

from django.db import migrations, models
import django.db.models.deletion
import oydin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('brand_image', models.ImageField(blank=True, upload_to='brand-images')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oydin.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to=oydin.models.upload_to)),
                ('description', models.CharField(max_length=500, null=True)),
                ('description_uz', models.CharField(max_length=500, null=True)),
                ('description_en', models.CharField(max_length=500, null=True)),
                ('description_ru', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('characteristic1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kommutatsiya quvvati')),
                ('characteristic3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operatsion xarakteristikasi')),
                ('characteristic2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qutblar soni')),
                ('extra_field_label', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika nomi")),
                ('extra_field_label_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika nomi")),
                ('extra_field_label_en', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika nomi")),
                ('extra_field_label_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika nomi")),
                ('extra_field_value', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika qiymati")),
                ('extra_field_value_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika qiymati")),
                ('extra_field_value_en', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika qiymati")),
                ('extra_field_value_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name="1.Qo'shimcha xarakteristika qiymati")),
                ('dop_field_label', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika nomi")),
                ('dop_field_label_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika nomi")),
                ('dop_field_label_en', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika nomi")),
                ('dop_field_label_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika nomi")),
                ('dop_field_value', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika qiymati")),
                ('dop_field_value_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika qiymati")),
                ('dop_field_value_en', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika qiymati")),
                ('dop_field_value_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name="2.Qo'shimcha xarakteristika qiymati")),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oydin.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oydin.category')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=oydin.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shots', to='oydin.product')),
            ],
            options={
                'verbose_name': 'Maxsulot rasmi',
                'verbose_name_plural': 'Maxsulot rasmlari',
            },
        ),
    ]
