# Generated by Django 4.0.10 on 2024-07-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brend', 'verbose_name_plural': 'Brendlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
