# Generated by Django 4.0.10 on 2024-07-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='brand_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
