# Generated by Django 4.0.10 on 2024-07-12 06:49

from django.db import migrations, models
import oydin.models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0002_product_brand_image_product_image_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to=oydin.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=oydin.models.upload_to),
        ),
    ]
