# Generated by Django 4.0.10 on 2024-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0002_alter_brand_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1.Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3.Xarakteristika qiymati'),
        ),
    ]
