# Generated by Django 4.0.10 on 2024-07-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0003_alter_product_characteristic1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristic3',
            new_name='characteristic_v',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic2',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
    ]
