# Generated by Django 4.0.10 on 2024-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0004_rename_characteristic3_product_characteristic_v_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristic_n',
            new_name='characteristic_n3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='characteristic_v',
            new_name='characteristic_v3',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n1_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n1_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n1_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n2_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n2_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n2_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n3_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n3_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_n3_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_v1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_v2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2.Xarakteristika qiymati'),
        ),
    ]
