# Generated by Django 4.0.10 on 2024-07-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0007_remove_brand_created_at_alter_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oydin.category'),
        ),
    ]
