# Generated by Django 4.0.10 on 2024-07-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0007_product_characteristic_n1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n1_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n1_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n1_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n2_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n2_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n2_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n3_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n3_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_n3_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_v1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_v2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristic_v3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_label_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_label_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_label_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_value_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_value_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop_field_value_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_label_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_label_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_label_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_value_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_value_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_value_uz',
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Xarakteristika nomi')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='Xarakteristika nomi')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Xarakteristika nomi')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Xarakteristika nomi')),
                ('value', models.CharField(max_length=50, verbose_name='Xarakteristika qiymati')),
                ('value_uz', models.CharField(max_length=50, null=True, verbose_name='Xarakteristika qiymati')),
                ('value_en', models.CharField(max_length=50, null=True, verbose_name='Xarakteristika qiymati')),
                ('value_ru', models.CharField(max_length=50, null=True, verbose_name='Xarakteristika qiymati')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='oydin.product')),
            ],
        ),
    ]
