# Generated by Django 4.0.10 on 2024-07-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0008_remove_product_characteristic_n1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Xarakteristika', 'verbose_name_plural': 'Xarakteristikalar'},
        ),
    ]
