# Generated by Django 4.0.10 on 2024-07-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0009_brand_name_en_brand_name_ru_brand_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_uz',
        ),
    ]
