# Generated by Django 4.0.10 on 2024-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0010_remove_brand_name_en_remove_brand_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
