# Generated by Django 4.0.10 on 2024-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0012_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dop_field_label',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_label_en',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_label_ru',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_label_uz',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_value',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_value_en',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='dop_field_value_uz',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_label',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_label_en',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_label_ru',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_label_uz',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_value',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_value_en',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_value_uz',
            field=models.CharField(max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika qiymati"),
        ),
    ]
