# Generated by Django 4.0.10 on 2024-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0013_product_dop_field_label_product_dop_field_label_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_field_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_field_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_field_label_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_field_label_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha xarakteristika nomi"),
        ),
    ]
