# Generated by Django 4.0.10 on 2024-07-26 06:29

from django.db import migrations, models
import oydin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0013_remove_orderitem_quantity_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[oydin.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[oydin.validators.validate_phone_number]),
        ),
    ]
