# Generated by Django 4.0.10 on 2024-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0014_alter_order_name_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
