# Generated by Django 4.0.10 on 2024-07-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0016_alter_product_dop_field_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_en',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
    ]
