# Generated by Django 4.0.10 on 2024-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0017_product_characteristic_product_characteristic_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic2',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2_en',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3_en',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Hos belgi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Hos belgi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic_en',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Hos belgi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Hos belgi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Hos belgi'),
        ),
    ]
