# Generated by Django 4.0.10 on 2025-08-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0017_news_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
    ]
