# Generated by Django 4.0.10 on 2024-07-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0018_product_characteristic2_product_characteristic2_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristic',
            new_name='characteristic1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='characteristic_en',
            new_name='characteristic1_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='characteristic_ru',
            new_name='characteristic1_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='characteristic_uz',
            new_name='characteristic1_uz',
        ),
    ]
