# Generated by Django 4.0.10 on 2025-08-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0018_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
    ]
