# Generated by Django 4.0.10 on 2024-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0019_rename_characteristic_product_characteristic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristic1',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1_en',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2_en',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3_en',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika'),
        ),
    ]
