# Generated by Django 4.0.10 on 2024-07-15 06:16

from django.db import migrations, models
import oydin.models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0020_alter_product_characteristic1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshots',
            name='image',
            field=models.ImageField(blank=True, upload_to=oydin.models.upload_to),
        ),
    ]
