# Generated by Django 4.0.10 on 2025-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0020_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='name_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika nomi'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='value_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
