# Generated by Django 4.0.10 on 2024-07-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0021_alter_productshots_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
