# Generated by Django 4.0.10 on 2024-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oydin', '0022_productshots_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic1value',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic1value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic1value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic1value_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2value',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic2value_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3value',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika qiymati'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic3value_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika qiymati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1_en',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic1_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='1.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2_en',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic2_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='2.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3_en',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic3_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='3.Xarakteristika nomi'),
        ),
    ]
